version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5
bridgecrew-commands:
  environment:
    PRISMA_API_URL: https://api-stage.prismacloud.io
jobs:
  build:
    executor: bridgecrew/default
    environment:
      PRISMA_API_URL: https://api-stage.prismacloud.io
    steps:
      - checkout
      - bridgecrew/scan:
          directory: .
          api-key-variable: BC_API_KEY
# version: 2.1
# orbs:
#   bridgecrew: bridgecrew/bridgecrew@1.0.3
# jobs:
#   bridgecrew-commands:
#     environment:
#       PRISMA_API_URL: https://api-stage.prismacloud.io
#     executor: bridgecrew/default
#     steps:
#       - checkout
#       - bridgecrew/install
#       - bridgecrew/scan:
#           directory: ./terraform
#           api-key-variable: BC_API_KEY
#           soft-fail: true
#           output: json
# workflows:
#   bridgecrew-scan:
#     jobs:
#       - bridgecrew/bridgecrew_scan:
#           directory: ./terraform
#           api-key-variable: BC_API_KEY
